const path = require('node:path');

const ROOT = path.join(__dirname, '..');

module.exports = {
    ROOT,

    // Diretórios e arquivos do projeto
    ASSETS_DIR: path.join(ROOT, 'assets'),
    DATA_DIR: path.join(ROOT, 'data'),
    CAMINHO_ESTADO_PERFIS: path.join(ROOT, 'data', '.perfis-estado.json'),
    CAMINHO_ESTADO_CARGOS_VIP: path.join(ROOT, 'data', '.cargos-vip.json'),
    CAMINHO_RASTREAMENTO_CARGOS_VIP: path.join(ROOT, 'data', '.cargos-vip-rastreamento.json'),
    CAMINHO_ESTADO_CAMPEONATO: path.join(ROOT, 'data', '.campeonato-estado.json'),
    CAMINHO_BANNER_CAMPEONATO: path.join(ROOT, 'assets', 'banner_champion.jpg'),
    CAMINHO_BANNER_PARCERIA: path.join(ROOT, 'assets', 'banner_parceria.jpg'),
    CAMINHO_BANNER_INFLUENCER: path.join(ROOT, 'banner_influencer.jpg'),
    CAMINHO_GIF_BAU: path.join(ROOT, 'assets', 'bau.gif'),

    // IDs de cargos - substitua pelos valores reais do seu servidor
    CARGO_NOVO_MEMBRO_ID: 'SEU_ID_CARGO_NOVO_MEMBRO',
    CARGO_STAFF_ID: 'SEU_ID_CARGO_STAFF',
    CARGO_OWNER_ID: 'SEU_ID_CARGO_OWNER',
    CARGO_SUB_OWNER_ID: 'SEU_ID_CARGO_SUB_OWNER',
    CARGO_ATENDIMENTO_ID: 'SEU_ID_CARGO_ATENDIMENTO',
    CARGO_BOOSTER_ID: 'SEU_ID_CARGO_BOOSTER',
    CARGO_MARCAR_PUNICOES_ID: 'SEU_ID_CARGO_MARCAR_PUNICOES',
    CARGO_PING_PARCERIA_ID: 'SEU_ID_CARGO_PING_PARCERIA',
    CARGO_PING_CALL_ID: 'SEU_ID_CARGO_PING_CALL',
    CARGO_PING_PARCERIAS_NOTIF_ID: 'SEU_ID_CARGO_PING_PARCERIAS_NOTIF',

    // IDs de canais - substitua pelos valores reais do seu servidor
    CANAL_BOAS_VINDAS_ID: 'SEU_ID_CANAL_BOAS_VINDAS',
    CANAL_CHAT_NOVO_MEMBRO_ID: 'SEU_ID_CANAL_CHAT_NOVO_MEMBRO',
    CANAL_REGRAS_ID: 'SEU_ID_CANAL_REGRAS',
    CANAL_SUPORTE_ID: 'SEU_ID_CANAL_SUPORTE',
    CANAL_PARCERIAS_ID: 'SEU_ID_CANAL_PARCERIAS',
    CANAL_PARCERIAS_BANNER_ID: 'SEU_ID_CANAL_PARCERIAS_BANNER',
    CANAL_INFLUENCER_BANNER_ID: 'SEU_ID_CANAL_INFLUENCER_BANNER',
    CANAL_CARGOS_ID: 'SEU_ID_CANAL_CARGOS',
    CANAL_LOJA_ID: 'SEU_ID_CANAL_LOJA',
    CANAL_CAMPEONATO_ID: 'SEU_ID_CANAL_CAMPEONATO',
    CANAL_OFICIALIZAR_ID: 'SEU_ID_CANAL_OFICIALIZAR',
    CANAL_OFICIALIZAR_CLUBE_ID: 'SEU_ID_CANAL_OFICIALIZAR_CLUBE',
    CANAL_BOOSTERS_ID: 'SEU_ID_CANAL_BOOSTERS',
    CANAL_ENTRADA_AUTOMATICA_ID: 'SEU_ID_CANAL_ENTRADA_AUTOMATICA',
    CANAL_LOGS_ID: 'SEU_ID_CANAL_LOGS',
    CANAL_LOG_CANAIS_ID: 'SEU_ID_CANAL_LOG_CANAIS',
    CANAL_LOG_CARGOS_ID: 'SEU_ID_CANAL_LOG_CARGOS',
    CANAL_LOG_CALLS_ID: 'SEU_ID_CANAL_LOG_CALLS',
    CANAL_LOG_AUTOMOD_ID: 'SEU_ID_CANAL_LOG_AUTOMOD',
    CANAL_LOG_PUNICOES_ID: 'SEU_ID_CANAL_LOG_PUNICOES',
    CANAL_LOG_TICKETS_ID: 'SEU_ID_CANAL_LOG_TICKETS',
    CANAL_LOG_BANS_ID: 'SEU_ID_CANAL_LOG_BANS',
    CANAL_NOTICIAS_STARS_ID: 'SEU_ID_CANAL_NOTICIAS',
    CANAL_PARCERIAS_NOTIF_ID: 'SEU_ID_CANAL_PARCERIAS_NOTIF',

    // IDs de categorias
    CATEGORIA_CALLS_PERSONALIZADAS_ID: 'SEU_ID_CATEGORIA_CALLS_PERSONALIZADAS',

    // Emojis e cores
    EMOJI_GEMA: '<:gema:SEU_EMOJI_GEMA>',
    EMOJI_BOTAO_COMPRAR_ID: 'SEU_EMOJI_BOTAO_COMPRAR',
    EMOJI_1_ID: 'SEU_EMOJI_1',
    EMOJI_2_ID: 'SEU_EMOJI_2',
    EMOJI_3_ID: 'SEU_EMOJI_3',
    EMOJI_BOTAO_SOLO_ID: 'SEU_EMOJI_BOTAO_SOLO',
    EMOJI_BOTAO_EQUIPE_ID: 'SEU_EMOJI_BOTAO_EQUIPE',
    EMOJI_CAMPEONATO_INFO_ID: 'SEU_EMOJI_CAMPEONATO_INFO',
    EMOJI_ASSUMIR_TICKET_ID: 'SEU_EMOJI_ASSUMIR_TICKET',
    EMOJI_FECHAR_TICKET_ID: 'SEU_EMOJI_FECHAR_TICKET',
    EMOJI_CARGOS_TROFEUS_ID: 'SEU_EMOJI_CARGOS_TROFEUS',
    EMOJI_CARGOS_RANQUEADA_ID: 'SEU_EMOJI_CARGOS_RANQUEADA',
    EMOJI_CARGOS_INFO_ID: 'SEU_EMOJI_CARGOS_INFO',
    EMOJI_CARGOS_PINGS_ID: 'SEU_EMOJI_CARGOS_PINGS',

    // Temporizadores e limites
    COOLDOWN_BAU_MS: 5 * 60 * 60 * 1000,
    HORA_EM_MS: 60 * 60 * 1000,
    DURACAO_CARGO_COMPRA_MS: 30 * 24 * 60 * 60 * 1000,
    LIMITE_INSCRICOES_SOLO: 30,
    LIMITE_INSCRICOES_EQUIPE: 8,
    LIMITE_CALL_CRIADA: 3,

    // Grupos de permissões
    CARGOS_AUTORIZADOS_DECISAO_PUNICAO: new Set([
        'SEU_ID_CARGO_OWNER',
        'SEU_ID_CARGO_SUB_OWNER'
    ]),
    CARGOS_AUTORIZADOS_ASSUMIR_TICKET: new Set([
        'SEU_ID_CARGO_OWNER',
        'SEU_ID_CARGO_SUB_OWNER',
        'SEU_ID_CARGO_ATENDIMENTO'
    ]),
    CARGOS_AUTORIZADOS_REC: new Set([
        'SEU_ID_CARGO_OWNER',
        'SEU_ID_CARGO_SUB_OWNER',
        'SEU_ID_CARGO_ATENDIMENTO'
    ]),
    CARGOS_EQUIPE: new Set([
        'SEU_ID_CARGO_OWNER',
        'SEU_ID_CARGO_SUB_OWNER',
        'SEU_ID_CARGO_ATENDIMENTO',
        'SEU_ID_CARGO_STAFF'
    ]),

    // Calls automáticas
    HUBS_DE_CALL: [
        { canalHubId: 'SEU_ID_HUB_CALL_TROFEUS', emoji: '🏆' },
        { canalHubId: 'SEU_ID_HUB_CALL_RANKED', emoji: '🎯' }
    ]
};